name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: docker build -f python/Dockerfile -t "parsertongue/odinson-example:python" python/
    - name: "Publish docker image (odinson-example:python)"
      if: github.ref == 'refs/heads/main'
      run: docker push "parsertongue/odinson-example:python"
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
